version: 2

builds:
  - id: araalert
    main: ./cmd/araalert
    binary: araalert
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ldflags: &ldflags
      - -s -w
      - -X main.ver={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags: [-trimpath]

  - id: arabackup
    main: ./cmd/arabackup
    binary: arabackup
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ldflags: *ldflags
    flags: [-trimpath]

  - id: aradashboard
    main: ./cmd/aradashboard
    binary: aradashboard
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ldflags: *ldflags
    flags: [-trimpath]

  - id: aradeploy
    main: ./cmd/aradeploy
    binary: aradeploy
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ldflags: *ldflags
    flags: [-trimpath]

  - id: aramanager
    main: ./cmd/aramanager
    binary: aramanager
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ldflags: *ldflags
    flags: [-trimpath]

  - id: aranotify
    main: ./cmd/aranotify
    binary: aranotify
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ldflags: *ldflags
    flags: [-trimpath]

  - id: arascanner
    main: ./cmd/arascanner
    binary: arascanner
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ldflags: *ldflags
    flags: [-trimpath]

  - id: aramdns
    main: ./cmd/aramdns
    binary: aramdns
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ldflags: *ldflags
    flags: [-trimpath]

archives:
  - id: aramanager
    formats: [tar.gz]
    builds:
      - aramanager
    name_template: "aramanager_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  - id: combined
    formats: [tar.gz]
    builds:
      - araalert
      - arabackup
      - aradashboard
      - aradeploy
      - aramanager
      - aranotify
      - arascanner
      - aramdns
    name_template: "arastack_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
