package deploy

import (
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/jdillenberger/arastack/internal/aradeploy/certs"
	"github.com/jdillenberger/arastack/internal/aradeploy/code"
	"github.com/jdillenberger/arastack/internal/aradeploy/compose"
	"github.com/jdillenberger/arastack/internal/aradeploy/routing"
	"github.com/jdillenberger/arastack/internal/aradeploy/template"
	"github.com/jdillenberger/arastack/pkg/aradeployconfig"
	"github.com/jdillenberger/arastack/pkg/cliutil"
	"github.com/jdillenberger/arastack/pkg/executil"
	"github.com/jdillenberger/arastack/pkg/portcheck"
	"gopkg.in/yaml.v3"
)

// StateFileName is the name of the deployment state file.
const StateFileName = aradeployconfig.StateFileName

// Manager handles app lifecycle operations.
type Manager struct {
	cfg      *ManagerConfig
	registry *template.Registry
	renderer *template.Renderer
	compose  *compose.Compose
	runner   *executil.Runner

	OnDeploy func(appName string, routing *routing.DeployedRoute)
	OnRemove func(appName string)
}

// NewServiceManager creates a lightweight manager for background service
// operations (e.g. certificate renewal) that don't require template
// rendering.
func NewServiceManager(cfg *ManagerConfig, runner *executil.Runner) *Manager {
	return &Manager{
		cfg:     cfg,
		compose: compose.New(runner, cfg.Docker.ComposeCommand),
		runner:  runner,
	}
}

// NewManager creates a new app manager.
func NewManager(cfg *ManagerConfig, runner *executil.Runner, tmplFS fs.FS) (*Manager, error) {
	registry, err := template.NewRegistry(tmplFS)
	if err != nil {
		return nil, fmt.Errorf("loading registry: %w", err)
	}

	return &Manager{
		cfg:      cfg,
		registry: registry,
		renderer: template.NewRenderer(registry),
		compose:  compose.New(runner, cfg.Docker.ComposeCommand),
		runner:   runner,
	}, nil
}

// Registry returns the app template registry.
func (m *Manager) Registry() *template.Registry {
	return m.registry
}

// Compose returns the compose wrapper.
func (m *Manager) Compose() *compose.Compose {
	return m.compose
}

// Config returns the manager configuration.
func (m *Manager) Config() *ManagerConfig {
	return m.cfg
}

// ensureTraefik auto-deploys traefik when routing is enabled and traefik
// is not yet deployed. Skipped when deploying traefik itself to prevent recursion.
func (m *Manager) ensureTraefik(appName string) error {
	if appName == "traefik" {
		return nil
	}
	if !m.cfg.Routing.Enabled || m.cfg.Routing.Provider != "traefik" {
		return nil
	}
	if m.isTraefikDeployed() {
		return nil
	}
	if _, ok := m.registry.Get("traefik"); !ok {
		return fmt.Errorf("routing is enabled but traefik template is not available; install it or disable routing")
	}

	fmt.Println("Routing is enabled — auto-deploying traefik...")
	if err := m.Deploy("traefik", DeployOptions{Confirm: true}); err != nil {
		return fmt.Errorf("auto-deploying traefik: %w", err)
	}
	fmt.Println("Traefik deployed successfully.")
	fmt.Println()
	return nil
}

// ensureNetwork creates the Docker network if it does not already exist.
func (m *Manager) ensureNetwork() error {
	network := m.cfg.Docker.DefaultNetwork
	if _, err := m.runner.Run(m.cfg.Docker.Runtime, "network", "create", network); err != nil {
		if _, inspectErr := m.runner.Run(m.cfg.Docker.Runtime, "network", "inspect", network); inspectErr != nil {
			return fmt.Errorf("ensuring docker network %s: %w", network, err)
		}
	}
	return nil
}

// Deploy deploys an app from its template with the given values.
func (m *Manager) Deploy(appName string, opts DeployOptions) error {
	if err := ValidateAppName(appName); err != nil {
		return err
	}

	lock, err := acquireLock(m.cfg.AppsDir, appName)
	if err != nil {
		return err
	}
	defer releaseLock(lock)

	meta, ok := m.registry.Get(appName)
	if !ok {
		return fmt.Errorf("unknown app template: %s", appName)
	}

	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(stateFilePath(appDir)); err == nil {
		return fmt.Errorf("app %s is already deployed (remove first)", appName)
	}
	mergedValues, autoGenerated, err := MergeValues(m.cfg, appName, meta, opts.Values)
	if err != nil {
		return err
	}

	// Validate port values against already-deployed apps
	portNames := meta.PortValueNameSet()
	if len(portNames) > 0 {
		usedPorts, usedErr := portcheck.UsedPorts(m.cfg.AppsDir)
		if usedErr != nil {
			slog.Warn("Failed to scan used ports", "error", usedErr)
		} else {
			for name := range portNames {
				val, ok := mergedValues[name]
				if !ok || val == "" {
					continue
				}
				port, err := strconv.Atoi(val)
				if err != nil {
					continue
				}
				if err := portcheck.ValidatePort(port, usedPorts, appName); err != nil {
					return fmt.Errorf("port conflict for %s=%s: %w", name, val, err)
				}
			}
		}
	}

	// Add HTTPS status
	if m.cfg.Routing.HTTPS.Enabled {
		mergedValues["https_enabled"] = "true"
		mergedValues["ca_cert_path"] = filepath.Join(m.cfg.DataPath("traefik"), "certs", "ca.crt")
	} else {
		mergedValues["https_enabled"] = "false"
		mergedValues["ca_cert_path"] = ""
	}

	// Auto-populate traefik-specific HTTPS values
	if appName == "traefik" && m.cfg.Routing.HTTPS.Enabled {
		mergedValues["acme_email"] = m.cfg.Routing.HTTPS.AcmeEmail
		mergedValues["certs_dir"] = filepath.Join(m.cfg.DataPath("traefik"), "certs")
	}

	// Generate local certificates for traefik (data dir must exist first)
	if appName == "traefik" && m.cfg.Routing.HTTPS.Enabled {
		if err := os.MkdirAll(m.cfg.DataPath("traefik"), 0o2775); err != nil { // #nosec G301 -- setgid needed for shared access
			return fmt.Errorf("creating traefik data directory: %w", err)
		}
		cm := certs.NewManager(m.cfg.DataPath("traefik"))
		certDomains := m.collectAllRoutingDomains(appName, mergedValues)
		if err := cm.EnsureCerts(certDomains); err != nil {
			return fmt.Errorf("generating local certificates: %w", err)
		}
		slog.Info("Local certificates generated", "ca_cert", cm.CACertPath())
	}

	// Compute routing BEFORE rendering so templates can use routing_domain/routing_url
	var deployedRouting *routing.DeployedRoute
	if m.cfg.Routing.Enabled && m.cfg.Routing.Provider == "traefik" {
		deployedRouting = routing.ComputeRouting(
			m.cfg.Hostname, m.cfg.Network.Domain, m.cfg.Routing.Domain,
			m.cfg.Routing.HTTPS.Enabled, appName, meta, mergedValues,
		)
		if deployedRouting.Enabled && len(deployedRouting.Domains) > 0 {
			scheme := "http"
			if m.cfg.Routing.HTTPS.Enabled {
				scheme = "https"
			}
			mergedValues["routing_domain"] = deployedRouting.Domains[0]
			mergedValues["routing_url"] = fmt.Sprintf("%s://%s", scheme, deployedRouting.Domains[0])
		}
		if mergedValues["forward_auth"] == "true" {
			deployedRouting.ForwardAuth = true
		}
	}

	// Fallback routing values
	if mergedValues["routing_domain"] == "" {
		mergedValues["routing_domain"] = appName + "-" + m.cfg.Hostname + "." + m.cfg.Network.Domain
	}
	if mergedValues["routing_url"] == "" {
		scheme := "http"
		if m.cfg.Routing.HTTPS.Enabled {
			scheme = "https"
		}
		mergedValues["routing_url"] = fmt.Sprintf("%s://%s", scheme, mergedValues["routing_domain"])
	}

	// Regenerate SAN cert to include this app's domain (non-traefik deploys)
	if appName != "traefik" && m.cfg.Routing.HTTPS.Enabled && m.isTraefikDeployed() {
		cm := certs.NewManager(m.cfg.DataPath("traefik"))
		certDomains := m.collectAllRoutingDomains(appName, mergedValues)
		if err := cm.EnsureCerts(certDomains); err != nil {
			slog.Warn("Failed to regenerate SAN cert", "error", err)
		}
	}

	// Render templates
	rendered, err := m.renderer.RenderAllFiles(appName, mergedValues)
	if err != nil {
		return fmt.Errorf("rendering templates: %w", err)
	}

	// Inject routing labels
	if deployedRouting != nil && deployedRouting.Enabled {
		provider := m.newRoutingProvider()
		if provider != nil {
			if composeContent, ok := rendered["docker-compose.yml"]; ok {
				modified, err := provider.InjectLabels(composeContent, appName, deployedRouting)
				if err != nil {
					slog.Warn("Failed to inject routing labels", "app", appName, "error", err)
				} else {
					rendered["docker-compose.yml"] = modified
				}
			}
		}
	}

	// Process code slots
	var codeSources []code.Source
	if meta.Code != nil && len(opts.Code) > 0 {
		codeSources, err = m.processCodeDeploy(appName, meta, opts.Code)
		if err != nil {
			return err
		}

		// Inject code volumes into compose
		if composeContent, ok := rendered["docker-compose.yml"]; ok {
			modified, err := code.InjectCodeVolumes(composeContent, meta.Code.Slots, codeSources, m.cfg.CodeDir, appName)
			if err != nil {
				slog.Warn("Failed to inject code volumes", "app", appName, "error", err)
			} else {
				rendered["docker-compose.yml"] = modified
			}
		}
	}
	if meta.Code != nil {
		if err := m.validateRequiredCodeSlots(meta, codeSources); err != nil {
			return err
		}
	}

	// Get static files
	staticFiles, err := m.renderer.CopyStaticFiles(appName)
	if err != nil {
		return fmt.Errorf("reading static files: %w", err)
	}

	if opts.DryRun {
		fmt.Println("Dry run — files that would be written:")
		for name, content := range rendered {
			fmt.Printf("\n--- %s ---\n%s", name, content)
		}
		for name := range staticFiles {
			fmt.Printf("\n--- %s (static) ---\n", name)
		}
		return nil
	}

	// Show confirmation summary
	if !opts.Confirm {
		printDeploySummary(appName, meta, mergedValues, autoGenerated, codeSources)
		if !AskConfirmation("Proceed with deploy?") {
			fmt.Println("Deploy cancelled.")
			return nil
		}
	}

	// Ensure traefik is deployed when routing is enabled
	if err := m.ensureTraefik(appName); err != nil {
		return err
	}

	// Ensure docker network exists
	if err := m.ensureNetwork(); err != nil {
		return err
	}

	// Create directories (group-writable + setgid to match parent)
	if err := os.MkdirAll(appDir, 0o2775); err != nil { // #nosec G301 -- setgid needed for shared access
		return fmt.Errorf("creating app directory: %w", err)
	}
	dataDir := m.cfg.DataPath(appName)
	if err := os.MkdirAll(dataDir, 0o2775); err != nil { // #nosec G301 -- setgid needed for shared access
		return fmt.Errorf("creating data directory: %w", err)
	}

	// Create volumes symlink
	volumesLink := filepath.Join(appDir, "volumes")
	_ = os.Remove(volumesLink)
	if err := os.Symlink(dataDir, volumesLink); err != nil {
		slog.Warn("Failed to create volumes symlink", "app", appName, "error", err)
	}

	// Generate CA bundle
	if m.cfg.Routing.HTTPS.Enabled && mergedValues["ca_cert_path"] != "" {
		if err := generateCABundle(mergedValues["ca_cert_path"], dataDir); err != nil {
			slog.Warn("Failed to generate CA bundle", "app", appName, "error", err)
		}
	}

	// Write rendered files
	for name, content := range rendered {
		outPath := filepath.Join(appDir, name)
		if err := os.MkdirAll(filepath.Dir(outPath), 0o750); err != nil {
			return fmt.Errorf("creating directory for %s: %w", name, err)
		}
		if err := os.WriteFile(outPath, []byte(content), 0o600); err != nil {
			return fmt.Errorf("writing %s: %w", name, err)
		}
	}

	// Write static files
	for name, data := range staticFiles {
		outPath := filepath.Join(appDir, name)
		if err := os.MkdirAll(filepath.Dir(outPath), 0o750); err != nil {
			return fmt.Errorf("creating directory for %s: %w", name, err)
		}
		if err := os.WriteFile(outPath, data, 0o644); err != nil { // #nosec G306 -- static files are bind-mounted into containers running as non-root
			return fmt.Errorf("writing %s: %w", name, err)
		}
	}

	// Save deployment info
	deployed := &DeployedApp{
		Name:       appName,
		Template:   appName,
		Values:     mergedValues,
		DeployedAt: time.Now(),
		Version:    meta.Version,
		Routing:    deployedRouting,
		Code:       codeSources,
	}
	if err := m.SaveDeployedInfo(appName, deployed); err != nil {
		return err
	}

	// Persist auto-generated secrets to data directory
	if err := saveSecrets(dataDir, collectAutoGenSecrets(meta, mergedValues)); err != nil {
		slog.Warn("Failed to save secrets to data directory", "app", appName, "error", err)
	}

	// Copy build sources into build context (cleaned up after build)
	var buildSourcePaths []string
	if meta.Code != nil && len(codeSources) > 0 {
		var copyErr error
		buildSourcePaths, copyErr = code.CopyBuildSources(appDir, meta.Code.Slots, codeSources, m.cfg.CodeDir, appName, m.runner)
		if copyErr != nil {
			return fmt.Errorf("copying build sources: %w", copyErr)
		}
	}

	// Run docker compose up
	composeErr := cliutil.RunWithSpinner(fmt.Sprintf("Deploying %s...", appName), func() error {
		if meta.RequiresBuild {
			_, err := m.compose.UpWithBuild(appDir)
			return err
		}
		_, err := m.compose.Up(appDir)
		return err
	})

	// Clean up build sources from app dir regardless of outcome
	code.CleanBuildSources(buildSourcePaths)

	if composeErr != nil {
		_, _ = m.compose.Down(appDir)
		_ = os.RemoveAll(appDir)
		_ = os.RemoveAll(dataDir)
		return fmt.Errorf("starting containers: %w", composeErr)
	}

	// Print access information
	hostname := mergedValues["hostname"]
	domain := mergedValues["domain"]
	fqdn := hostname + "." + domain

	fmt.Printf("\nApp %s deployed successfully.\n\n", appName)
	for _, p := range meta.Ports {
		if p.ValueName != "" {
			if portVal, ok := mergedValues[p.ValueName]; ok {
				scheme := "http"
				if strings.Contains(strings.ToLower(p.Description), "https") {
					scheme = "https"
				}
				fmt.Printf("  %-20s %s://%s:%s\n", p.Description+":", scheme, fqdn, portVal)
			}
		} else {
			fmt.Printf("  %-20s :%d (container :%d)\n", p.Description+":", p.Host, p.Container)
		}
	}
	fmt.Printf("  %-20s %s\n", "Data:", m.cfg.DataPath(appName))

	if deployed.Routing != nil && deployed.Routing.Enabled && len(deployed.Routing.Domains) > 0 {
		scheme := "http"
		if m.cfg.Routing.HTTPS.Enabled {
			scheme = "https"
		}
		for _, d := range deployed.Routing.Domains {
			fmt.Printf("  %-20s %s://%s\n", "URL:", scheme, d)
		}
	}

	fmt.Println()

	printPostDeployInfo(meta, mergedValues)

	// Execute post-deploy hooks
	if meta.Hooks != nil {
		if err := executeHooks(meta.Hooks.PostDeploy, mergedValues, m.runner); err != nil {
			return fmt.Errorf("post-deploy hook: %w", err)
		}
	}

	// Invoke deploy callback
	if m.OnDeploy != nil {
		m.OnDeploy(appName, deployed.Routing)
	}

	return nil
}

// Remove removes a deployed app.
func (m *Manager) Remove(appName string, keepData bool) error {
	if err := ValidateAppName(appName); err != nil {
		return err
	}

	lock, err := acquireLock(m.cfg.AppsDir, appName)
	if err != nil {
		return err
	}
	defer releaseLock(lock)

	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return fmt.Errorf("app %s is not deployed", appName)
	}

	// Prevent removing traefik while other routed apps depend on it
	if appName == "traefik" && m.cfg.Routing.Enabled {
		if deployed, err := m.ListDeployed(); err == nil {
			var dependents []string
			for _, name := range deployed {
				if name == "traefik" {
					continue
				}
				info, err := m.GetDeployedInfo(name)
				if err != nil {
					continue
				}
				if info.Routing != nil && info.Routing.Enabled {
					dependents = append(dependents, name)
				}
			}
			if len(dependents) > 0 {
				return fmt.Errorf("cannot remove traefik: the following apps depend on it for routing: %s\nRemove them first, or disable routing in the config",
					strings.Join(dependents, ", "))
			}
		}
	}

	// Prevent removing authelia while other apps depend on it for forward auth
	if appName == "authelia" {
		if deployed, err := m.ListDeployed(); err == nil {
			var dependents []string
			for _, name := range deployed {
				if name == "authelia" {
					continue
				}
				info, err := m.GetDeployedInfo(name)
				if err != nil {
					continue
				}
				if info.Routing != nil && info.Routing.ForwardAuth {
					dependents = append(dependents, name)
				}
			}
			if len(dependents) > 0 {
				return fmt.Errorf("cannot remove authelia: the following apps depend on it for forward auth: %s\nRemove them first",
					strings.Join(dependents, ", "))
			}
		}
	}

	meta, ok := m.registry.Get(appName)
	if ok && meta.Hooks != nil {
		if err := executeHooks(meta.Hooks.PreRemove, map[string]string{
			"app_name": appName,
			"hostname": m.cfg.Hostname,
			"domain":   m.cfg.Network.Domain,
			"data_dir": m.cfg.DataPath(appName),
		}, m.runner); err != nil {
			return fmt.Errorf("pre-remove hook: %w", err)
		}
	}

	// Persist secrets to data directory before removing app directory.
	// This ensures secrets survive remove/deploy cycles when data is kept,
	// including for deployments created before secret persistence was added.
	if keepData && ok { // ok: template metadata available from registry.Get above
		if info, err := m.GetDeployedInfo(appName); err == nil {
			dataDir := m.cfg.DataPath(appName)
			if err := saveSecrets(dataDir, collectAutoGenSecrets(meta, info.Values)); err != nil {
				slog.Warn("Failed to save secrets on remove", "app", appName, "error", err)
			}
		} else {
			slog.Warn("Failed to read deploy state for secret persistence", "app", appName, "error", err)
		}
	}

	fmt.Printf("Stopping %s...\n", appName)
	if _, err := m.compose.Down(appDir); err != nil {
		fmt.Printf("Warning: failed to stop containers: %v\n", err)
	}

	if err := os.RemoveAll(appDir); err != nil {
		return fmt.Errorf("removing app directory: %w", err)
	}

	// Clean up code directory
	codeDir := m.cfg.CodePath(appName)
	_ = os.RemoveAll(codeDir)

	if m.OnRemove != nil {
		m.OnRemove(appName)
	}

	if !keepData {
		dataDir := m.cfg.DataPath(appName)
		if err := os.RemoveAll(dataDir); err != nil {
			if _, dockerErr := m.runner.Run(m.cfg.Docker.Runtime, "run", "--rm",
				"-v", dataDir+":/data", "alpine", "sh", "-c", "rm -rf /data/*"); dockerErr != nil {
				return fmt.Errorf("removing data directory: %w (docker fallback also failed: %w)", err, dockerErr)
			}
			_ = os.RemoveAll(dataDir)
		}
		fmt.Printf("App %s removed (including data).\n", appName)
	} else {
		fmt.Printf("App %s removed (data kept at %s).\n", appName, m.cfg.DataPath(appName))
	}

	return nil
}

// Start starts a deployed app's containers.
func (m *Manager) Start(appName string) error {
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return fmt.Errorf("app %s is not deployed", appName)
	}
	_, err := m.compose.Start(appDir)
	return err
}

// Stop stops a deployed app's containers.
func (m *Manager) Stop(appName string) error {
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return fmt.Errorf("app %s is not deployed", appName)
	}
	_, err := m.compose.Stop(appDir)
	return err
}

// Restart restarts a deployed app's containers.
func (m *Manager) Restart(appName string) error {
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return fmt.Errorf("app %s is not deployed", appName)
	}
	_, err := m.compose.Restart(appDir)
	return err
}

// Status returns the container status for an app.
func (m *Manager) Status(appName string) (string, error) {
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return "", fmt.Errorf("app %s is not deployed", appName)
	}
	result, err := m.compose.PS(appDir)
	if err != nil {
		return "", err
	}
	return result.Stdout, nil
}

// Update pulls the latest images and recreates containers for a deployed app.
func (m *Manager) Update(appName string) error {
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return fmt.Errorf("app %s is not deployed", appName)
	}

	fmt.Printf("Pulling latest images for %s...\n", appName)
	if _, err := m.compose.Pull(appDir); err != nil {
		return fmt.Errorf("pulling images: %w", err)
	}

	fmt.Printf("Recreating containers for %s...\n", appName)
	_, err := m.compose.Up(appDir)
	return err
}

// ListDeployed returns the names of all deployed apps.
func (m *Manager) ListDeployed() ([]string, error) {
	entries, err := os.ReadDir(m.cfg.AppsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var apps []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		appDir := filepath.Join(m.cfg.AppsDir, entry.Name())
		if _, err := os.Stat(stateFilePath(appDir)); err == nil {
			apps = append(apps, entry.Name())
		}
	}
	return apps, nil
}

// GetDeployedInfo reads the deployment info for an app.
func (m *Manager) GetDeployedInfo(appName string) (*DeployedApp, error) {
	appDir := m.cfg.AppDir(appName)
	infoPath := stateFilePath(appDir)

	data, err := os.ReadFile(infoPath) // #nosec G304 -- path is constructed internally
	if err != nil {
		return nil, fmt.Errorf("reading deploy info: %w", err)
	}

	var info DeployedApp
	if err := yaml.Unmarshal(data, &info); err != nil {
		return nil, fmt.Errorf("parsing deploy info: %w", err)
	}
	return &info, nil
}

// SaveDeployedInfo writes updated deployment info for an app.
// It writes to a temporary file first, then atomically renames it so that
// concurrent readers (arabackup, aradashboard) never see a partial file.
func (m *Manager) SaveDeployedInfo(appName string, info *DeployedApp) error {
	appDir := m.cfg.AppDir(appName)
	infoPath := stateFilePath(appDir)
	data, err := yaml.Marshal(info)
	if err != nil {
		return fmt.Errorf("serializing deploy info: %w", err)
	}

	tmp, err := os.CreateTemp(appDir, ".aradeploy.yaml.tmp.*")
	if err != nil {
		return fmt.Errorf("creating temp file: %w", err)
	}
	tmpPath := tmp.Name()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("writing temp file: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("syncing temp file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("closing temp file: %w", err)
	}
	if err := os.Chmod(tmpPath, 0o600); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("setting permissions: %w", err)
	}
	if err := os.Rename(tmpPath, infoPath); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("renaming temp file: %w", err)
	}
	return nil
}

// SecretEntry holds a single secret value with metadata for display.
type SecretEntry struct {
	Name        string `json:"name"`
	Value       string `json:"value"`
	Description string `json:"description"`
	UserFacing  bool   `json:"user_facing"`
}

// GetSecrets returns the secrets for a deployed app.
func (m *Manager) GetSecrets(appName string) ([]SecretEntry, error) {
	info, err := m.GetDeployedInfo(appName)
	if err != nil {
		return nil, fmt.Errorf("app %s is not deployed: %w", appName, err)
	}

	meta, ok := m.registry.Get(appName)
	if !ok {
		return nil, fmt.Errorf("unknown app template: %s", appName)
	}

	var secrets []SecretEntry
	for _, v := range meta.Values {
		if !v.Secret {
			continue
		}
		val, exists := info.Values[v.Name]
		if !exists || val == "" {
			continue
		}
		secrets = append(secrets, SecretEntry{
			Name:        v.Name,
			Value:       val,
			Description: v.Description,
			UserFacing:  v.UserFacing,
		})
	}
	return secrets, nil
}

// RegenerateCompose re-renders the template for a deployed app and re-injects
// routing labels if applicable.
func (m *Manager) RegenerateCompose(appName string) error {
	info, err := m.GetDeployedInfo(appName)
	if err != nil {
		return fmt.Errorf("reading deploy info: %w", err)
	}

	meta, ok := m.registry.Get(appName)
	if !ok {
		return fmt.Errorf("unknown app template: %s", appName)
	}

	// Refresh routing values from current config
	if m.cfg.Routing.Enabled && m.cfg.Routing.HTTPS.Enabled {
		info.Values["https_enabled"] = "true"
		info.Values["ca_cert_path"] = filepath.Join(m.cfg.DataPath("traefik"), "certs", "ca.crt")
	} else {
		info.Values["https_enabled"] = "false"
		info.Values["ca_cert_path"] = ""
	}
	if m.cfg.Routing.Enabled && info.Routing != nil && info.Routing.Enabled && len(info.Routing.Domains) > 0 {
		scheme := "http"
		if m.cfg.Routing.HTTPS.Enabled {
			scheme = "https"
		}
		info.Values["routing_domain"] = info.Routing.Domains[0]
		info.Values["routing_url"] = fmt.Sprintf("%s://%s", scheme, info.Routing.Domains[0])
	}
	if info.Values["routing_domain"] == "" {
		info.Values["routing_domain"] = appName + "-" + m.cfg.Hostname + "." + m.cfg.Network.Domain
	}
	if info.Values["routing_url"] == "" {
		scheme := "http"
		if m.cfg.Routing.HTTPS.Enabled {
			scheme = "https"
		}
		info.Values["routing_url"] = fmt.Sprintf("%s://%s", scheme, info.Values["routing_domain"])
	}

	// Regenerate CA bundle if HTTPS is enabled
	if m.cfg.Routing.Enabled && m.cfg.Routing.HTTPS.Enabled && info.Values["ca_cert_path"] != "" {
		dataDir := m.cfg.DataPath(appName)
		if err := generateCABundle(info.Values["ca_cert_path"], dataDir); err != nil {
			slog.Warn("Failed to generate CA bundle", "app", appName, "error", err)
		}
	}

	// Re-render templates
	rendered, err := m.renderer.RenderAllFiles(appName, info.Values)
	if err != nil {
		return fmt.Errorf("rendering templates: %w", err)
	}

	// Inject routing labels if enabled
	if m.cfg.Routing.Enabled && m.cfg.Routing.Provider == "traefik" && info.Routing != nil && info.Routing.Enabled {
		provider := m.newRoutingProvider()
		if provider != nil {
			if composeContent, ok := rendered["docker-compose.yml"]; ok {
				modified, err := provider.InjectLabels(composeContent, appName, info.Routing)
				if err != nil {
					return fmt.Errorf("injecting labels: %w", err)
				}
				rendered["docker-compose.yml"] = modified
			}
		}
	}

	// Re-inject code volumes if applicable
	if len(info.Code) > 0 && meta.Code != nil {
		if composeContent, ok := rendered["docker-compose.yml"]; ok {
			modified, err := code.InjectCodeVolumes(composeContent, meta.Code.Slots, info.Code, m.cfg.CodeDir, appName)
			if err != nil {
				slog.Warn("Failed to inject code volumes", "app", appName, "error", err)
			} else {
				rendered["docker-compose.yml"] = modified
			}
		}
	}

	// Write updated compose file
	appDir := m.cfg.AppDir(appName)
	if composeContent, ok := rendered["docker-compose.yml"]; ok {
		composePath := appDir + "/docker-compose.yml"
		if err := os.WriteFile(composePath, []byte(composeContent), 0o600); err != nil {
			return fmt.Errorf("writing docker-compose.yml: %w", err)
		}
	}

	// Apply changes
	if meta.RequiresBuild {
		_, err = m.compose.UpWithBuild(appDir)
	} else {
		_, err = m.compose.Up(appDir)
	}
	if err != nil {
		return fmt.Errorf("restarting containers: %w", err)
	}

	return nil
}

// newRoutingProvider creates the configured routing provider.
func (m *Manager) newRoutingProvider() routing.Provider {
	if m.cfg.Routing.Provider != "traefik" {
		return nil
	}
	return &routing.TraefikProvider{
		Domain:       m.cfg.Routing.Domain,
		HTTPSEnabled: m.cfg.Routing.HTTPS.Enabled,
		AcmeEmail:    m.cfg.Routing.HTTPS.AcmeEmail,
		Network:      m.cfg.Docker.DefaultNetwork,
	}
}

func stateFilePath(appDir string) string {
	return filepath.Join(appDir, StateFileName)
}

// isTraefikDeployed checks if traefik is currently deployed.
func (m *Manager) isTraefikDeployed() bool {
	return m.isAppDeployed("traefik")
}

// IsAutheliaDeployed checks if authelia is currently deployed.
func (m *Manager) IsAutheliaDeployed() bool {
	return m.isAppDeployed("authelia")
}

// isAppDeployed checks if a given app is currently deployed.
func (m *Manager) isAppDeployed(appName string) bool {
	deployed, err := m.ListDeployed()
	if err != nil {
		return false
	}
	for _, d := range deployed {
		if d == appName {
			return true
		}
	}
	return false
}

// collectAllRoutingDomains gathers all local routing domains from deployed apps.
func (m *Manager) collectAllRoutingDomains(currentApp string, mergedValues map[string]string) []string {
	domainSet := make(map[string]bool)

	dashboardDomain := m.cfg.RoutingDomain()
	if routing.IsLocalDomain(dashboardDomain) {
		domainSet[dashboardDomain] = true
	}

	if rd, ok := mergedValues["routing_domain"]; ok && rd != "" && routing.IsLocalDomain(rd) {
		domainSet[rd] = true
	}

	deployed, err := m.ListDeployed()
	if err == nil {
		for _, name := range deployed {
			if name == currentApp {
				continue
			}
			info, err := m.GetDeployedInfo(name)
			if err != nil {
				continue
			}
			if info.Routing != nil && info.Routing.Enabled {
				for _, d := range info.Routing.Domains {
					if routing.IsLocalDomain(d) {
						domainSet[d] = true
					}
				}
			}
		}
	}

	domains := make([]string, 0, len(domainSet))
	for d := range domainSet {
		domains = append(domains, d)
	}
	sort.Strings(domains)
	return domains
}

// RenewCerts checks whether the local TLS certificates are expiring and
// regenerates them if needed. When certificates are renewed it restarts
// traefik and regenerates the CA bundle for every deployed app.
func (m *Manager) RenewCerts() error {
	if !m.cfg.Routing.HTTPS.Enabled {
		return nil
	}

	cm := certs.NewManager(m.cfg.DataPath("traefik"))
	certDomains := m.collectAllRoutingDomains("", nil)
	if len(certDomains) == 0 {
		return nil
	}

	renewed, err := cm.EnsureCertsIfNeeded(certDomains)
	if err != nil {
		return fmt.Errorf("renewing certificates: %w", err)
	}
	if !renewed {
		return nil
	}

	slog.Info("Certificates renewed, restarting traefik")
	if m.isTraefikDeployed() {
		if err := m.Restart("traefik"); err != nil {
			slog.Error("Failed to restart traefik after cert renewal", "error", err)
		}
	}

	// Regenerate CA bundles for all deployed apps.
	caCertPath := cm.CACertPath()
	deployed, err := m.ListDeployed()
	if err != nil {
		return fmt.Errorf("listing deployed apps: %w", err)
	}
	for _, appName := range deployed {
		dataDir := m.cfg.DataPath(appName)
		if err := generateCABundle(caCertPath, dataDir); err != nil {
			slog.Warn("Failed to regenerate CA bundle", "app", appName, "error", err)
		}
	}

	slog.Info("CA bundles regenerated for all deployed apps")
	return nil
}

// generateCABundle creates a CA certificate bundle.
// If the local CA cert is not available (e.g. traefik not yet deployed),
// it falls back to using just the system CA bundle so the mount still works.
func generateCABundle(caCertPath, dataDir string) error {
	systemBundle, err := os.ReadFile("/etc/ssl/certs/ca-certificates.crt") // #nosec G304 -- well-known system path
	if err != nil {
		return fmt.Errorf("reading system CA bundle: %w", err)
	}

	bundle := systemBundle
	localCA, err := os.ReadFile(caCertPath) // #nosec G304 -- path is constructed internally
	if err != nil {
		slog.Warn("Local CA cert not available, using system bundle only", "path", caCertPath, "error", err)
	} else {
		bundle = make([]byte, 0, len(systemBundle)+1+len(localCA))
		bundle = append(bundle, systemBundle...)
		bundle = append(bundle, '\n')
		bundle = append(bundle, localCA...)
	}

	bundlePath := filepath.Join(dataDir, "ca-bundle.crt")
	return os.WriteFile(bundlePath, bundle, 0o644) // #nosec G306,G703 -- CA bundle is public; path is constructed internally
}

// printDeploySummary shows what will be deployed before asking for confirmation.
func printDeploySummary(appName string, meta *template.AppMeta, mergedValues map[string]string, autoGenerated map[string]bool, codeSources []code.Source) {
	fmt.Printf("\n=== Deploy Summary ===\n\n")
	fmt.Printf("  App:      %s\n", appName)
	fmt.Printf("  Version:  %s\n", meta.Version)
	fmt.Println()

	if len(meta.Ports) > 0 {
		fmt.Println("  Ports:")
		for _, p := range meta.Ports {
			hostPort := fmt.Sprintf("%d", p.Host)
			if p.ValueName != "" {
				if v, ok := mergedValues[p.ValueName]; ok {
					hostPort = v
				}
			}
			fmt.Printf("    %s:%d/%s  (%s)\n", hostPort, p.Container, p.Protocol, p.Description)
		}
		fmt.Println()
	}

	if len(meta.Volumes) > 0 {
		fmt.Println("  Volumes:")
		dataDir := mergedValues["data_dir"]
		for _, v := range meta.Volumes {
			fmt.Printf("    %s/%s -> %s  (%s)\n", dataDir, v.Name, v.Container, v.Description)
		}
		fmt.Println()
	}

	if len(codeSources) > 0 {
		fmt.Println("  Code sources:")
		for _, cs := range codeSources {
			label := cs.Slot
			if cs.Name != "" {
				label += "/" + cs.Name
			}
			extra := cs.Type
			if cs.Branch != "" {
				extra += ", branch: " + cs.Branch
			}
			fmt.Printf("    %-25s %s  (%s)\n", label, cs.Source, extra)
		}
		fmt.Println()
	}

	if len(autoGenerated) > 0 {
		fmt.Println("  Auto-generated secrets:")
		for name := range autoGenerated {
			fmt.Printf("    %s  [generated]\n", name)
		}
		fmt.Println()
	}
}

// AskConfirmation prompts the user for y/n and returns true if they confirm.
//
// Deprecated: use cliutil.AskConfirmation instead.
func AskConfirmation(prompt string) bool {
	return cliutil.AskConfirmation(prompt)
}

// processCodeDeploy parses --code flags, clones/syncs code sources, and returns CodeSource entries.
func (m *Manager) processCodeDeploy(appName string, meta *template.AppMeta, codeFlags map[string]string) ([]code.Source, error) {
	if meta.Code == nil {
		return nil, nil
	}

	slotMap := make(map[string]template.CodeSlot)
	for _, s := range meta.Code.Slots {
		slotMap[s.Name] = s
	}

	codeMgr := code.NewManager(m.cfg.CodeDir, m.runner)
	var sources []code.Source

	for key, sourceSpec := range codeFlags {
		// Parse key: "slot" or "slot/name"
		slotName, name := parseCodeKey(key)

		slot, ok := slotMap[slotName]
		if !ok {
			return nil, fmt.Errorf("unknown code slot %q (template defines: %s)", slotName, availableSlotNames(meta))
		}

		if slot.Multiple && name == "" {
			return nil, fmt.Errorf("code slot %q supports multiple items — use %s/<name>=<source>", slotName, slotName)
		}
		if !slot.Multiple && name != "" {
			return nil, fmt.Errorf("code slot %q does not support multiple items — use %s=<source>", slotName, slotName)
		}

		if slot.InjectMode() == "build" && !meta.RequiresBuild {
			return nil, fmt.Errorf("code slot %q uses inject=build but template does not have requires_build: true", slotName)
		}

		// Parse source#branch
		source, branch := parseSourceBranch(sourceSpec)

		cs, err := codeMgr.Add(appName, slot, name, source, branch)
		if err != nil {
			return nil, fmt.Errorf("adding code for %s: %w", key, err)
		}
		sources = append(sources, cs)
	}

	return sources, nil
}

// validateRequiredCodeSlots checks that all required code slots have at least one source.
func (m *Manager) validateRequiredCodeSlots(meta *template.AppMeta, sources []code.Source) error {
	if meta.Code == nil {
		return nil
	}

	provided := make(map[string]bool)
	for _, cs := range sources {
		provided[cs.Slot] = true
	}

	for _, slot := range meta.Code.Slots {
		if slot.Required && !provided[slot.Name] {
			return fmt.Errorf("required code slot %q is not provided — use --code %s=<source>", slot.Name, slot.Name)
		}
	}
	return nil
}

// parseCodeKey splits a code key like "slot/name" into slot and name parts.
func parseCodeKey(key string) (slot, name string) {
	if idx := strings.Index(key, "/"); idx >= 0 {
		return key[:idx], key[idx+1:]
	}
	return key, ""
}

// parseSourceBranch splits a source spec like "url#branch" into source and branch.
func parseSourceBranch(spec string) (source, branch string) {
	if idx := strings.LastIndex(spec, "#"); idx >= 0 {
		return spec[:idx], spec[idx+1:]
	}
	return spec, ""
}

// availableSlotNames returns a comma-separated list of slot names from the template.
func availableSlotNames(meta *template.AppMeta) string {
	if meta.Code == nil {
		return "(none)"
	}
	var names []string
	for _, s := range meta.Code.Slots {
		names = append(names, s.Name)
	}
	return strings.Join(names, ", ")
}

// printPostDeployInfo displays post-deploy information including user-facing secrets.
// It consolidates access URL, login credentials (username from post_deploy_info +
// user_facing secret values), and setup notes into one block.
func printPostDeployInfo(meta *template.AppMeta, values map[string]string) {
	info := meta.PostDeployInfo

	// Collect all user-facing secrets that have a value.
	var secrets []struct{ name, value, desc string }
	for _, v := range meta.Values {
		if !v.UserFacing || !v.Secret {
			continue
		}
		val := values[v.Name]
		if val == "" {
			continue
		}
		secrets = append(secrets, struct{ name, value, desc string }{v.Name, val, v.Description})
	}

	if info == nil && len(secrets) == 0 {
		return
	}

	fmt.Println("--- Post-Deploy Info ---")

	if info != nil && info.AccessURL != "" {
		if rendered, err := renderTemplate(info.AccessURL, values); err == nil {
			fmt.Printf("  Access URL:    %s\n", rendered)
		}
	}

	// Show login credentials: username from post_deploy_info + user-facing secrets.
	hasCredentials := info != nil && info.Credentials != ""
	if hasCredentials || len(secrets) > 0 {
		fmt.Println()
		fmt.Println("  Login credentials:")
		if hasCredentials {
			if rendered, err := renderTemplate(info.Credentials, values); err == nil {
				fmt.Printf("    %s\n", rendered)
			}
		}
		for _, e := range secrets {
			label := e.desc
			if label == "" {
				label = e.name
			}
			fmt.Printf("    %-25s %s\n", label+":", e.value)
		}
	}

	if info != nil && len(info.Notes) > 0 {
		fmt.Println()
		fmt.Println("  Notes:")
		for i, note := range info.Notes {
			if rendered, err := renderTemplate(note, values); err == nil {
				fmt.Printf("    %d. %s\n", i+1, rendered)
			}
		}
	}

	if len(secrets) > 0 {
		fmt.Println()
		fmt.Println("  View secrets later with: aradeploy secrets " + meta.Name)
	}

	fmt.Println()
}
