package deploy

import (
	"bufio"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/jdillenberger/arastack/internal/aradeploy/certs"
	"github.com/jdillenberger/arastack/internal/aradeploy/compose"
	"github.com/jdillenberger/arastack/internal/aradeploy/routing"
	"github.com/jdillenberger/arastack/internal/aradeploy/template"
	"github.com/jdillenberger/arastack/pkg/executil"
	"gopkg.in/yaml.v3"
)

// StateFileName is the name of the deployment state file.
const StateFileName = ".aradeploy.yaml"

// Manager handles app lifecycle operations.
type Manager struct {
	cfg      *ManagerConfig
	registry *template.Registry
	renderer *template.Renderer
	compose  *compose.Compose
	runner   *executil.Runner

	OnDeploy func(appName string, routing *routing.DeployedRoute)
	OnRemove func(appName string)
}

// NewManager creates a new app manager.
func NewManager(cfg *ManagerConfig, runner *executil.Runner, tmplFS fs.FS) (*Manager, error) {
	registry, err := template.NewRegistry(tmplFS)
	if err != nil {
		return nil, fmt.Errorf("loading registry: %w", err)
	}

	return &Manager{
		cfg:      cfg,
		registry: registry,
		renderer: template.NewRenderer(registry),
		compose:  compose.New(runner, cfg.Docker.ComposeCommand),
		runner:   runner,
	}, nil
}

// Registry returns the app template registry.
func (m *Manager) Registry() *template.Registry {
	return m.registry
}

// Compose returns the compose wrapper.
func (m *Manager) Compose() *compose.Compose {
	return m.compose
}

// Config returns the manager configuration.
func (m *Manager) Config() *ManagerConfig {
	return m.cfg
}

// ensureNetwork creates the Docker network if it does not already exist.
func (m *Manager) ensureNetwork() error {
	network := m.cfg.Docker.DefaultNetwork
	if _, err := m.runner.Run(m.cfg.Docker.Runtime, "network", "create", network); err != nil {
		if _, inspectErr := m.runner.Run(m.cfg.Docker.Runtime, "network", "inspect", network); inspectErr != nil {
			return fmt.Errorf("ensuring docker network %s: %w", network, err)
		}
	}
	return nil
}

// Deploy deploys an app from its template with the given values.
func (m *Manager) Deploy(appName string, opts DeployOptions) error {
	if err := ValidateAppName(appName); err != nil {
		return err
	}

	lock, err := acquireLock(m.cfg.AppsDir, appName)
	if err != nil {
		return err
	}
	defer releaseLock(lock)

	meta, ok := m.registry.Get(appName)
	if !ok {
		return fmt.Errorf("unknown app template: %s", appName)
	}

	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(stateFilePath(appDir)); err == nil {
		return fmt.Errorf("app %s is already deployed (remove first)", appName)
	}
	mergedValues, autoGenerated, err := MergeValues(m.cfg, appName, meta, opts.Values)
	if err != nil {
		return err
	}

	// Add HTTPS status
	if m.cfg.Routing.HTTPS.Enabled {
		mergedValues["https_enabled"] = "true"
		mergedValues["ca_cert_path"] = filepath.Join(m.cfg.DataPath("traefik"), "certs", "ca.crt")
	} else {
		mergedValues["https_enabled"] = "false"
		mergedValues["ca_cert_path"] = ""
	}

	// Auto-populate traefik-specific HTTPS values
	if appName == "traefik" && m.cfg.Routing.HTTPS.Enabled {
		mergedValues["acme_email"] = m.cfg.Routing.HTTPS.AcmeEmail
		mergedValues["certs_dir"] = filepath.Join(m.cfg.DataPath("traefik"), "certs")
	}

	// Generate local certificates for traefik
	if appName == "traefik" && m.cfg.Routing.HTTPS.Enabled {
		cm := certs.NewManager(m.cfg.DataPath("traefik"))
		certDomains := m.collectAllRoutingDomains(appName, mergedValues)
		if err := cm.EnsureCerts(certDomains); err != nil {
			return fmt.Errorf("generating local certificates: %w", err)
		}
		slog.Info("Local certificates generated", "ca_cert", cm.CACertPath())
	}

	// Compute routing BEFORE rendering so templates can use routing_domain/routing_url
	var deployedRouting *routing.DeployedRoute
	if m.cfg.Routing.Enabled && m.cfg.Routing.Provider == "traefik" {
		deployedRouting = routing.ComputeRouting(
			m.cfg.Hostname, m.cfg.Network.Domain, m.cfg.Routing.Domain,
			m.cfg.Routing.HTTPS.Enabled, appName, meta, mergedValues,
		)
		if deployedRouting.Enabled && len(deployedRouting.Domains) > 0 {
			scheme := "http"
			if m.cfg.Routing.HTTPS.Enabled {
				scheme = "https"
			}
			mergedValues["routing_domain"] = deployedRouting.Domains[0]
			mergedValues["routing_url"] = fmt.Sprintf("%s://%s", scheme, deployedRouting.Domains[0])
		}
	}

	// Fallback routing values
	if mergedValues["routing_domain"] == "" {
		mergedValues["routing_domain"] = appName + "-" + m.cfg.Hostname + "." + m.cfg.Network.Domain
	}
	if mergedValues["routing_url"] == "" {
		scheme := "http"
		if m.cfg.Routing.HTTPS.Enabled {
			scheme = "https"
		}
		mergedValues["routing_url"] = fmt.Sprintf("%s://%s", scheme, mergedValues["routing_domain"])
	}

	// Regenerate SAN cert to include this app's domain (non-traefik deploys)
	if appName != "traefik" && m.cfg.Routing.HTTPS.Enabled && m.isTraefikDeployed() {
		cm := certs.NewManager(m.cfg.DataPath("traefik"))
		certDomains := m.collectAllRoutingDomains(appName, mergedValues)
		if err := cm.EnsureCerts(certDomains); err != nil {
			slog.Warn("Failed to regenerate SAN cert", "error", err)
		}
	}

	// Render templates
	rendered, err := m.renderer.RenderAllFiles(appName, mergedValues)
	if err != nil {
		return fmt.Errorf("rendering templates: %w", err)
	}

	// Inject routing labels
	if deployedRouting != nil && deployedRouting.Enabled {
		provider := m.newRoutingProvider()
		if provider != nil {
			if composeContent, ok := rendered["docker-compose.yml"]; ok {
				modified, err := provider.InjectLabels(composeContent, appName, deployedRouting)
				if err != nil {
					slog.Warn("Failed to inject routing labels", "app", appName, "error", err)
				} else {
					rendered["docker-compose.yml"] = modified
				}
			}
		}
	}

	// Get static files
	staticFiles, err := m.renderer.CopyStaticFiles(appName)
	if err != nil {
		return fmt.Errorf("reading static files: %w", err)
	}

	if opts.DryRun {
		fmt.Println("Dry run — files that would be written:")
		for name, content := range rendered {
			fmt.Printf("\n--- %s ---\n%s", name, content)
		}
		for name := range staticFiles {
			fmt.Printf("\n--- %s (static) ---\n", name)
		}
		return nil
	}

	// Show confirmation summary
	if !opts.Confirm {
		printDeploySummary(appName, meta, mergedValues, autoGenerated)
		if !AskConfirmation("Proceed with deploy?") {
			fmt.Println("Deploy cancelled.")
			return nil
		}
	}

	// Ensure docker network exists
	if err := m.ensureNetwork(); err != nil {
		return err
	}

	// Create directories
	if err := os.MkdirAll(appDir, 0o755); err != nil {
		return fmt.Errorf("creating app directory: %w", err)
	}
	dataDir := m.cfg.DataPath(appName)
	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		return fmt.Errorf("creating data directory: %w", err)
	}

	// Create volumes symlink
	volumesLink := filepath.Join(appDir, "volumes")
	_ = os.Remove(volumesLink)
	if err := os.Symlink(dataDir, volumesLink); err != nil {
		slog.Warn("Failed to create volumes symlink", "app", appName, "error", err)
	}

	// Generate CA bundle
	if m.cfg.Routing.HTTPS.Enabled && mergedValues["ca_cert_path"] != "" {
		if err := generateCABundle(mergedValues["ca_cert_path"], dataDir); err != nil {
			slog.Warn("Failed to generate CA bundle", "app", appName, "error", err)
		}
	}

	// Write rendered files
	for name, content := range rendered {
		outPath := filepath.Join(appDir, name)
		if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
			return fmt.Errorf("creating directory for %s: %w", name, err)
		}
		if err := os.WriteFile(outPath, []byte(content), 0o600); err != nil {
			return fmt.Errorf("writing %s: %w", name, err)
		}
	}

	// Write static files
	for name, data := range staticFiles {
		outPath := filepath.Join(appDir, name)
		if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
			return fmt.Errorf("creating directory for %s: %w", name, err)
		}
		if err := os.WriteFile(outPath, data, 0o600); err != nil {
			return fmt.Errorf("writing %s: %w", name, err)
		}
	}

	// Save deployment info
	deployed := &DeployedApp{
		Name:       appName,
		Template:   appName,
		Values:     mergedValues,
		DeployedAt: time.Now(),
		Version:    meta.Version,
		Routing:    deployedRouting,
	}
	if err := m.SaveDeployedInfo(appName, deployed); err != nil {
		return err
	}

	// Run docker compose up
	fmt.Printf("Starting %s...\n", appName)
	var composeErr error
	if meta.RequiresBuild {
		_, composeErr = m.compose.UpWithBuild(appDir)
	} else {
		_, composeErr = m.compose.Up(appDir)
	}
	if composeErr != nil {
		_, _ = m.compose.Down(appDir)
		_ = os.RemoveAll(appDir)
		_ = os.RemoveAll(dataDir)
		return fmt.Errorf("starting containers: %w", composeErr)
	}

	// Print access information
	hostname := mergedValues["hostname"]
	domain := mergedValues["domain"]
	fqdn := hostname + "." + domain

	fmt.Printf("\nApp %s deployed successfully.\n\n", appName)
	for _, p := range meta.Ports {
		if p.ValueName != "" {
			if portVal, ok := mergedValues[p.ValueName]; ok {
				scheme := "http"
				if strings.Contains(strings.ToLower(p.Description), "https") {
					scheme = "https"
				}
				fmt.Printf("  %-20s %s://%s:%s\n", p.Description+":", scheme, fqdn, portVal)
			}
		} else {
			fmt.Printf("  %-20s :%d (container :%d)\n", p.Description+":", p.Host, p.Container)
		}
	}
	fmt.Printf("  %-20s %s\n", "Data:", m.cfg.DataPath(appName))

	if deployed.Routing != nil && deployed.Routing.Enabled && len(deployed.Routing.Domains) > 0 {
		scheme := "http"
		if m.cfg.Routing.HTTPS.Enabled {
			scheme = "https"
		}
		for _, d := range deployed.Routing.Domains {
			fmt.Printf("  %-20s %s://%s\n", "URL:", scheme, d)
		}
	}

	fmt.Println()

	if meta.PostDeployInfo != nil {
		printPostDeployInfo(meta.PostDeployInfo, mergedValues)
	}

	// Execute post-deploy hooks
	if meta.Hooks != nil {
		executeHooks(meta.Hooks.PostDeploy, mergedValues, m.runner)
	}

	// Invoke deploy callback
	if m.OnDeploy != nil {
		m.OnDeploy(appName, deployed.Routing)
	}

	return nil
}

// Remove removes a deployed app.
func (m *Manager) Remove(appName string, keepData bool) error {
	if err := ValidateAppName(appName); err != nil {
		return err
	}

	lock, err := acquireLock(m.cfg.AppsDir, appName)
	if err != nil {
		return err
	}
	defer releaseLock(lock)

	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return fmt.Errorf("app %s is not deployed", appName)
	}

	meta, ok := m.registry.Get(appName)
	if ok && meta.Hooks != nil {
		executeHooks(meta.Hooks.PreRemove, map[string]string{
			"app_name": appName,
			"hostname": m.cfg.Hostname,
			"domain":   m.cfg.Network.Domain,
			"data_dir": m.cfg.DataPath(appName),
		}, m.runner)
	}

	fmt.Printf("Stopping %s...\n", appName)
	if _, err := m.compose.Down(appDir); err != nil {
		fmt.Printf("Warning: failed to stop containers: %v\n", err)
	}

	if err := os.RemoveAll(appDir); err != nil {
		return fmt.Errorf("removing app directory: %w", err)
	}

	if m.OnRemove != nil {
		m.OnRemove(appName)
	}

	if !keepData {
		dataDir := m.cfg.DataPath(appName)
		if err := os.RemoveAll(dataDir); err != nil {
			if _, dockerErr := m.runner.Run(m.cfg.Docker.Runtime, "run", "--rm",
				"-v", dataDir+":/data", "alpine", "sh", "-c", "rm -rf /data/*"); dockerErr != nil {
				return fmt.Errorf("removing data directory: %w (docker fallback also failed: %v)", err, dockerErr)
			}
			_ = os.RemoveAll(dataDir)
		}
		fmt.Printf("App %s removed (including data).\n", appName)
	} else {
		fmt.Printf("App %s removed (data kept at %s).\n", appName, m.cfg.DataPath(appName))
	}

	return nil
}

// Start starts a deployed app's containers.
func (m *Manager) Start(appName string) error {
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return fmt.Errorf("app %s is not deployed", appName)
	}
	_, err := m.compose.Start(appDir)
	return err
}

// Stop stops a deployed app's containers.
func (m *Manager) Stop(appName string) error {
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return fmt.Errorf("app %s is not deployed", appName)
	}
	_, err := m.compose.Stop(appDir)
	return err
}

// Restart restarts a deployed app's containers.
func (m *Manager) Restart(appName string) error {
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return fmt.Errorf("app %s is not deployed", appName)
	}
	_, err := m.compose.Restart(appDir)
	return err
}

// Status returns the container status for an app.
func (m *Manager) Status(appName string) (string, error) {
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return "", fmt.Errorf("app %s is not deployed", appName)
	}
	result, err := m.compose.PS(appDir)
	if err != nil {
		return "", err
	}
	return result.Stdout, nil
}

// Update pulls the latest images and recreates containers for a deployed app.
func (m *Manager) Update(appName string) error {
	appDir := m.cfg.AppDir(appName)
	if _, err := os.Stat(appDir); os.IsNotExist(err) {
		return fmt.Errorf("app %s is not deployed", appName)
	}

	fmt.Printf("Pulling latest images for %s...\n", appName)
	if _, err := m.compose.Pull(appDir); err != nil {
		return fmt.Errorf("pulling images: %w", err)
	}

	fmt.Printf("Recreating containers for %s...\n", appName)
	_, err := m.compose.Up(appDir)
	return err
}

// ListDeployed returns the names of all deployed apps.
func (m *Manager) ListDeployed() ([]string, error) {
	entries, err := os.ReadDir(m.cfg.AppsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var apps []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		appDir := filepath.Join(m.cfg.AppsDir, entry.Name())
		if _, err := os.Stat(stateFilePath(appDir)); err == nil {
			apps = append(apps, entry.Name())
		}
	}
	return apps, nil
}

// GetDeployedInfo reads the deployment info for an app.
func (m *Manager) GetDeployedInfo(appName string) (*DeployedApp, error) {
	appDir := m.cfg.AppDir(appName)
	infoPath := stateFilePath(appDir)

	data, err := os.ReadFile(infoPath)
	if err != nil {
		return nil, fmt.Errorf("reading deploy info: %w", err)
	}

	var info DeployedApp
	if err := yaml.Unmarshal(data, &info); err != nil {
		return nil, fmt.Errorf("parsing deploy info: %w", err)
	}
	return &info, nil
}

// SaveDeployedInfo writes updated deployment info for an app.
// It writes to a temporary file first, then atomically renames it so that
// concurrent readers (arabackup, aradashboard) never see a partial file.
func (m *Manager) SaveDeployedInfo(appName string, info *DeployedApp) error {
	appDir := m.cfg.AppDir(appName)
	infoPath := stateFilePath(appDir)
	data, err := yaml.Marshal(info)
	if err != nil {
		return fmt.Errorf("serializing deploy info: %w", err)
	}

	tmp, err := os.CreateTemp(appDir, ".aradeploy.yaml.tmp.*")
	if err != nil {
		return fmt.Errorf("creating temp file: %w", err)
	}
	tmpPath := tmp.Name()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("writing temp file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("closing temp file: %w", err)
	}
	if err := os.Chmod(tmpPath, 0o600); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("setting permissions: %w", err)
	}
	if err := os.Rename(tmpPath, infoPath); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("renaming temp file: %w", err)
	}
	return nil
}

// RegenerateCompose re-renders the template for a deployed app and re-injects
// routing labels if applicable.
func (m *Manager) RegenerateCompose(appName string) error {
	info, err := m.GetDeployedInfo(appName)
	if err != nil {
		return fmt.Errorf("reading deploy info: %w", err)
	}

	meta, ok := m.registry.Get(appName)
	if !ok {
		return fmt.Errorf("unknown app template: %s", appName)
	}

	// Refresh routing values from current config
	if m.cfg.Routing.Enabled && m.cfg.Routing.HTTPS.Enabled {
		info.Values["https_enabled"] = "true"
		info.Values["ca_cert_path"] = filepath.Join(m.cfg.DataPath("traefik"), "certs", "ca.crt")
	} else {
		info.Values["https_enabled"] = "false"
		info.Values["ca_cert_path"] = ""
	}
	if m.cfg.Routing.Enabled && info.Routing != nil && info.Routing.Enabled && len(info.Routing.Domains) > 0 {
		scheme := "http"
		if m.cfg.Routing.HTTPS.Enabled {
			scheme = "https"
		}
		info.Values["routing_domain"] = info.Routing.Domains[0]
		info.Values["routing_url"] = fmt.Sprintf("%s://%s", scheme, info.Routing.Domains[0])
	}
	if info.Values["routing_domain"] == "" {
		info.Values["routing_domain"] = appName + "-" + m.cfg.Hostname + "." + m.cfg.Network.Domain
	}
	if info.Values["routing_url"] == "" {
		scheme := "http"
		if m.cfg.Routing.HTTPS.Enabled {
			scheme = "https"
		}
		info.Values["routing_url"] = fmt.Sprintf("%s://%s", scheme, info.Values["routing_domain"])
	}

	// Regenerate CA bundle if HTTPS is enabled
	if m.cfg.Routing.Enabled && m.cfg.Routing.HTTPS.Enabled && info.Values["ca_cert_path"] != "" {
		dataDir := m.cfg.DataPath(appName)
		if err := generateCABundle(info.Values["ca_cert_path"], dataDir); err != nil {
			slog.Warn("Failed to generate CA bundle", "app", appName, "error", err)
		}
	}

	// Re-render templates
	rendered, err := m.renderer.RenderAllFiles(appName, info.Values)
	if err != nil {
		return fmt.Errorf("rendering templates: %w", err)
	}

	// Inject routing labels if enabled
	if m.cfg.Routing.Enabled && m.cfg.Routing.Provider == "traefik" && info.Routing != nil && info.Routing.Enabled {
		provider := m.newRoutingProvider()
		if provider != nil {
			if composeContent, ok := rendered["docker-compose.yml"]; ok {
				modified, err := provider.InjectLabels(composeContent, appName, info.Routing)
				if err != nil {
					return fmt.Errorf("injecting labels: %w", err)
				}
				rendered["docker-compose.yml"] = modified
			}
		}
	}

	// Write updated compose file
	appDir := m.cfg.AppDir(appName)
	if composeContent, ok := rendered["docker-compose.yml"]; ok {
		composePath := appDir + "/docker-compose.yml"
		if err := os.WriteFile(composePath, []byte(composeContent), 0o600); err != nil {
			return fmt.Errorf("writing docker-compose.yml: %w", err)
		}
	}

	// Apply changes
	if meta.RequiresBuild {
		_, err = m.compose.UpWithBuild(appDir)
	} else {
		_, err = m.compose.Up(appDir)
	}
	if err != nil {
		return fmt.Errorf("restarting containers: %w", err)
	}

	return nil
}

// newRoutingProvider creates the configured routing provider.
func (m *Manager) newRoutingProvider() routing.Provider {
	if m.cfg.Routing.Provider != "traefik" {
		return nil
	}
	return &routing.TraefikProvider{
		Domain:       m.cfg.Routing.Domain,
		HTTPSEnabled: m.cfg.Routing.HTTPS.Enabled,
		AcmeEmail:    m.cfg.Routing.HTTPS.AcmeEmail,
		Network:      m.cfg.Docker.DefaultNetwork,
	}
}

func stateFilePath(appDir string) string {
	return filepath.Join(appDir, StateFileName)
}

// isTraefikDeployed checks if traefik is currently deployed.
func (m *Manager) isTraefikDeployed() bool {
	deployed, err := m.ListDeployed()
	if err != nil {
		return false
	}
	for _, d := range deployed {
		if d == "traefik" {
			return true
		}
	}
	return false
}

// collectAllRoutingDomains gathers all local routing domains from deployed apps.
func (m *Manager) collectAllRoutingDomains(currentApp string, mergedValues map[string]string) []string {
	domainSet := make(map[string]bool)

	dashboardDomain := m.cfg.RoutingDomain()
	if routing.IsLocalDomain(dashboardDomain) {
		domainSet[dashboardDomain] = true
	}

	if rd, ok := mergedValues["routing_domain"]; ok && rd != "" && routing.IsLocalDomain(rd) {
		domainSet[rd] = true
	}

	deployed, err := m.ListDeployed()
	if err == nil {
		for _, name := range deployed {
			if name == currentApp {
				continue
			}
			info, err := m.GetDeployedInfo(name)
			if err != nil {
				continue
			}
			if info.Routing != nil && info.Routing.Enabled {
				for _, d := range info.Routing.Domains {
					if routing.IsLocalDomain(d) {
						domainSet[d] = true
					}
				}
			}
		}
	}

	domains := make([]string, 0, len(domainSet))
	for d := range domainSet {
		domains = append(domains, d)
	}
	sort.Strings(domains)
	return domains
}

// generateCABundle creates a CA certificate bundle.
func generateCABundle(caCertPath, dataDir string) error {
	systemBundle, err := os.ReadFile("/etc/ssl/certs/ca-certificates.crt")
	if err != nil {
		return fmt.Errorf("reading system CA bundle: %w", err)
	}
	localCA, err := os.ReadFile(caCertPath)
	if err != nil {
		return fmt.Errorf("reading local CA cert: %w", err)
	}

	bundlePath := filepath.Join(dataDir, "ca-bundle.crt")
	bundle := make([]byte, 0, len(systemBundle)+1+len(localCA))
	bundle = append(bundle, systemBundle...)
	bundle = append(bundle, '\n')
	bundle = append(bundle, localCA...)
	return os.WriteFile(bundlePath, bundle, 0o644)
}

// printDeploySummary shows what will be deployed before asking for confirmation.
func printDeploySummary(appName string, meta *template.AppMeta, mergedValues map[string]string, autoGenerated map[string]bool) {
	fmt.Printf("\n=== Deploy Summary ===\n\n")
	fmt.Printf("  App:      %s\n", appName)
	fmt.Printf("  Version:  %s\n", meta.Version)
	fmt.Println()

	if len(meta.Ports) > 0 {
		fmt.Println("  Ports:")
		for _, p := range meta.Ports {
			hostPort := fmt.Sprintf("%d", p.Host)
			if p.ValueName != "" {
				if v, ok := mergedValues[p.ValueName]; ok {
					hostPort = v
				}
			}
			fmt.Printf("    %s:%d/%s  (%s)\n", hostPort, p.Container, p.Protocol, p.Description)
		}
		fmt.Println()
	}

	if len(meta.Volumes) > 0 {
		fmt.Println("  Volumes:")
		dataDir := mergedValues["data_dir"]
		for _, v := range meta.Volumes {
			fmt.Printf("    %s/%s -> %s  (%s)\n", dataDir, v.Name, v.Container, v.Description)
		}
		fmt.Println()
	}

	if len(autoGenerated) > 0 {
		fmt.Println("  Auto-generated secrets:")
		for name := range autoGenerated {
			fmt.Printf("    %s  [generated]\n", name)
		}
		fmt.Println()
	}
}

// AskConfirmation prompts the user for y/n and returns true if they confirm.
func AskConfirmation(prompt string) bool {
	fmt.Printf("%s [y/N]: ", prompt)
	scanner := bufio.NewScanner(os.Stdin)
	if scanner.Scan() {
		answer := strings.TrimSpace(strings.ToLower(scanner.Text()))
		return answer == "y" || answer == "yes"
	}
	return false
}

// printPostDeployInfo displays post-deploy information to the user.
func printPostDeployInfo(info *template.PostDeployInfo, values map[string]string) {
	fmt.Println("--- Post-Deploy Info ---")

	if info.AccessURL != "" {
		if rendered, err := renderTemplate(info.AccessURL, values); err == nil {
			fmt.Printf("  Access URL:    %s\n", rendered)
		}
	}

	if info.Credentials != "" {
		if rendered, err := renderTemplate(info.Credentials, values); err == nil {
			fmt.Printf("  Credentials:   %s\n", rendered)
		}
	}

	if len(info.Notes) > 0 {
		fmt.Println("  First-time setup:")
		for i, note := range info.Notes {
			if rendered, err := renderTemplate(note, values); err == nil {
				fmt.Printf("    %d. %s\n", i+1, rendered)
			}
		}
	}

	fmt.Println()
}
