package deploy

import (
	"fmt"
	"strconv"

	"github.com/google/uuid"

	"github.com/jdillenberger/arastack/internal/aradeploy/template"
)

// MergeValues builds the final values map by merging defaults, user-supplied values,
// auto-generated secrets, and system values.
func MergeValues(cfg *ManagerConfig, appName string, meta *template.AppMeta, userValues map[string]string) (merged map[string]string, autoGenerated map[string]bool, err error) {
	merged = make(map[string]string)
	autoGenerated = make(map[string]bool)

	// Start with defaults from app.yaml
	for _, v := range meta.Values {
		if v.Default != "" {
			merged[v.Name] = v.Default
		}
	}

	// Override with user-supplied values
	for k, v := range userValues {
		merged[k] = v
	}

	// Auto-generate secrets
	for _, v := range meta.Values {
		if v.AutoGen != "" && merged[v.Name] == "" {
			switch v.AutoGen {
			case "password":
				pw, err := template.GenPassword()
				if err != nil {
					return nil, nil, fmt.Errorf("generating password for %s: %w", v.Name, err)
				}
				merged[v.Name] = pw
				autoGenerated[v.Name] = true
			case "uuid":
				merged[v.Name] = uuid.New().String()
				autoGenerated[v.Name] = true
			}
		}
	}

	// Ensure timezone has a default
	if merged["timezone"] == "" {
		merged["timezone"] = "UTC"
	}

	// Validate required values
	for _, v := range meta.Values {
		if v.Required && merged[v.Name] == "" {
			return nil, nil, fmt.Errorf("required value %q is not set and has no default", v.Name)
		}
	}

	// Add standard system values
	merged["hostname"] = cfg.Hostname
	merged["domain"] = cfg.Network.Domain
	merged["data_dir"] = cfg.DataPath(appName)
	merged["app_name"] = appName
	merged["network"] = cfg.Docker.DefaultNetwork
	if merged["web_port"] == "" {
		merged["web_port"] = strconv.Itoa(cfg.Network.WebPort)
	}

	return merged, autoGenerated, nil
}
