package deploy

import (
	"fmt"
	"net"
	"net/url"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"

	"github.com/jdillenberger/arastack/internal/aradeploy/template"
)

// MergeValues builds the final values map by merging defaults, user-supplied values,
// auto-generated secrets, and system values.
func MergeValues(cfg *ManagerConfig, appName string, meta *template.AppMeta, userValues map[string]string) (merged map[string]string, autoGenerated map[string]bool, err error) {
	merged = make(map[string]string)
	autoGenerated = make(map[string]bool)

	// Start with defaults from app.yaml
	for _, v := range meta.Values {
		if v.Default != "" {
			merged[v.Name] = v.Default
		}
	}

	// Override with user-supplied values
	for k, v := range userValues {
		merged[k] = v
	}

	// Auto-generate secrets
	for _, v := range meta.Values {
		if v.AutoGen != "" && merged[v.Name] == "" {
			switch v.AutoGen {
			case "password":
				pw, err := template.GenPassword()
				if err != nil {
					return nil, nil, fmt.Errorf("generating password for %s: %w", v.Name, err)
				}
				merged[v.Name] = pw
				autoGenerated[v.Name] = true
			case "uuid":
				merged[v.Name] = uuid.New().String()
				autoGenerated[v.Name] = true
			}
		}
	}

	// Ensure timezone has a default
	if merged["timezone"] == "" {
		merged["timezone"] = "UTC"
	}

	// Validate required values
	for _, v := range meta.Values {
		if v.Required && merged[v.Name] == "" {
			return nil, nil, fmt.Errorf("required value %q is not set and has no default", v.Name)
		}
	}

	// Validate values against template-defined validators.
	for _, v := range meta.Values {
		if v.Validation == "" {
			continue
		}
		val := merged[v.Name]
		if val == "" {
			continue // empty values validated by Required check above
		}
		if err := validateValue(v.Name, val, v.Validation); err != nil {
			return nil, nil, err
		}
	}

	// Add standard system values
	merged["hostname"] = cfg.Hostname
	merged["domain"] = cfg.Network.Domain
	merged["data_dir"] = cfg.DataPath(appName)
	merged["app_name"] = appName
	merged["network"] = cfg.Docker.DefaultNetwork
	if merged["web_port"] == "" {
		merged["web_port"] = strconv.Itoa(cfg.Network.WebPort)
	}

	return merged, autoGenerated, nil
}

var emailRe = regexp.MustCompile(`^[^@\s]+@[^@\s]+\.[^@\s]+$`)

// hostnameRe follows RFC 952 / RFC 1123: labels of alphanumerics and hyphens, dot-separated.
var hostnameRe = regexp.MustCompile(`^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$`)

// validateValue checks a single value against a named validator.
func validateValue(name, value, validation string) error {
	for _, v := range strings.Split(validation, ",") {
		v = strings.TrimSpace(v)
		if v == "" {
			continue
		}
		if err := runValidator(name, value, v); err != nil {
			return err
		}
	}
	return nil
}

func runValidator(name, value, validator string) error {
	switch validator {
	case "nonempty":
		if strings.TrimSpace(value) == "" {
			return fmt.Errorf("value %q: must not be empty", name)
		}
	case "port":
		p, err := strconv.Atoi(value)
		if err != nil || p < 1 || p > 65535 {
			return fmt.Errorf("value %q (%s): must be a valid port (1-65535)", name, value)
		}
	case "email":
		if !emailRe.MatchString(value) {
			return fmt.Errorf("value %q (%s): must be a valid email address", name, value)
		}
	case "hostname":
		if !hostnameRe.MatchString(value) || len(value) > 253 {
			return fmt.Errorf("value %q (%s): must be a valid hostname (RFC 952)", name, value)
		}
		// Also check individual label length.
		for _, label := range strings.Split(value, ".") {
			if len(label) > 63 {
				return fmt.Errorf("value %q (%s): hostname label exceeds 63 characters", name, value)
			}
		}
	case "url":
		u, err := url.Parse(value)
		if err != nil || u.Scheme == "" || u.Host == "" {
			return fmt.Errorf("value %q (%s): must be a valid URL", name, value)
		}
	case "ip":
		if net.ParseIP(value) == nil {
			return fmt.Errorf("value %q (%s): must be a valid IP address", name, value)
		}
	default:
		return fmt.Errorf("value %q: unknown validator %q", name, validator)
	}
	return nil
}
