package deploy

import (
	"fmt"
	"log/slog"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"gopkg.in/yaml.v3"

	"github.com/jdillenberger/arastack/internal/aradeploy/template"
	"github.com/jdillenberger/arastack/pkg/portcheck"
)

// SecretsFileName is the name of the persisted secrets file stored in the data directory.
const SecretsFileName = ".aradeploy-secrets.yaml"

// MergeValues builds the final values map by merging defaults, user-supplied values,
// auto-generated secrets, and system values.
func MergeValues(cfg *ManagerConfig, appName string, meta *template.AppMeta, userValues map[string]string) (merged map[string]string, autoGenerated map[string]bool, err error) {
	merged = make(map[string]string)
	autoGenerated = make(map[string]bool)

	// Start with defaults from app.yaml
	for _, v := range meta.Values {
		if v.Default != "" {
			merged[v.Name] = v.Default
		}
	}

	// Override with user-supplied values
	for k, v := range userValues {
		merged[k] = v
	}

	// Load saved secrets from data directory (persisted across remove/deploy cycles)
	savedSecrets := loadSavedSecrets(cfg.DataPath(appName))

	// Auto-generate secrets (reuse saved secrets if available)
	for _, v := range meta.Values {
		if v.AutoGen != "" && merged[v.Name] == "" {
			if saved, ok := savedSecrets[v.Name]; ok {
				merged[v.Name] = saved
				autoGenerated[v.Name] = true
				continue
			}
			switch v.AutoGen {
			case "password":
				pw, err := template.GenPassword()
				if err != nil {
					return nil, nil, fmt.Errorf("generating password for %s: %w", v.Name, err)
				}
				merged[v.Name] = pw
				autoGenerated[v.Name] = true
			case "uuid":
				merged[v.Name] = uuid.New().String()
				autoGenerated[v.Name] = true
			}
		}
	}

	// Ensure timezone has a default (detect host timezone)
	if merged["timezone"] == "" {
		merged["timezone"] = hostTimezone()
	}

	// Validate required values
	for _, v := range meta.Values {
		if v.Required && merged[v.Name] == "" {
			return nil, nil, fmt.Errorf("required value %q is not set and has no default", v.Name)
		}
	}

	// Validate values against template-defined validators.
	for _, v := range meta.Values {
		if v.Validation == "" {
			continue
		}
		val := merged[v.Name]
		if val == "" {
			continue // empty values validated by Required check above
		}
		if err := validateValue(v.Name, val, v.Validation); err != nil {
			return nil, nil, err
		}
	}

	// Add standard system values
	merged["hostname"] = cfg.Hostname
	merged["domain"] = cfg.Network.Domain
	merged["data_dir"] = cfg.DataPath(appName)
	merged["code_dir"] = cfg.CodePath(appName)
	merged["app_name"] = appName
	merged["network"] = cfg.Docker.DefaultNetwork
	merged["routing_base_domain"] = cfg.RoutingDomain()
	if merged["web_port"] == "" {
		usedPorts, _ := portcheck.UsedPorts(cfg.AppsDir)
		free := portcheck.NextFreePort(cfg.Network.WebPort, usedPorts)
		merged["web_port"] = strconv.Itoa(free)
	}

	return merged, autoGenerated, nil
}

var emailRe = regexp.MustCompile(`^[^@\s]+@[^@\s]+\.[^@\s]+$`)

// hostnameRe follows RFC 952 / RFC 1123: labels of alphanumerics and hyphens, dot-separated.
var hostnameRe = regexp.MustCompile(`^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$`)

// validateValue checks a single value against a named validator.
func validateValue(name, value, validation string) error {
	for _, v := range strings.Split(validation, ",") {
		v = strings.TrimSpace(v)
		if v == "" {
			continue
		}
		if err := runValidator(name, value, v); err != nil {
			return err
		}
	}
	return nil
}

// hostTimezone attempts to detect the host's IANA timezone.
// It checks the TZ environment variable, then /etc/timezone (Debian/Ubuntu),
// then resolves the /etc/localtime symlink (RHEL/Arch/Alpine), and falls back to "UTC".
func hostTimezone() string {
	// Method 1: TZ environment variable (POSIX standard)
	if tz := os.Getenv("TZ"); tz != "" && !strings.EqualFold(tz, "local") && tz[0] != ':' && tz[0] != '/' {
		if _, err := time.LoadLocation(tz); err == nil {
			return tz
		}
	}

	// Method 2: /etc/timezone (Debian/Ubuntu)
	if data, err := os.ReadFile("/etc/timezone"); err == nil {
		tz := strings.TrimSpace(string(data))
		if _, err := time.LoadLocation(tz); err == nil {
			return tz
		}
	}

	// Method 3: /etc/localtime symlink -> /usr/share/zoneinfo/<tz>
	if target, err := filepath.EvalSymlinks("/etc/localtime"); err == nil {
		const prefix = "/usr/share/zoneinfo/"
		if strings.HasPrefix(target, prefix) {
			tz := strings.TrimPrefix(target, prefix)
			tz = strings.TrimPrefix(tz, "posix/")
			tz = strings.TrimPrefix(tz, "right/")
			if _, err := time.LoadLocation(tz); err == nil {
				return tz
			}
		}
	}

	return "UTC"
}

func runValidator(name, value, validator string) error {
	switch validator {
	case "nonempty":
		if strings.TrimSpace(value) == "" {
			return fmt.Errorf("value %q: must not be empty", name)
		}
	case "port":
		p, err := strconv.Atoi(value)
		if err != nil || p < 1 || p > 65535 {
			return fmt.Errorf("value %q (%s): must be a valid port (1-65535)", name, value)
		}
	case "email":
		if !emailRe.MatchString(value) {
			return fmt.Errorf("value %q (%s): must be a valid email address", name, value)
		}
	case "hostname":
		if !hostnameRe.MatchString(value) || len(value) > 253 {
			return fmt.Errorf("value %q (%s): must be a valid hostname (RFC 952)", name, value)
		}
		// Also check individual label length.
		for _, label := range strings.Split(value, ".") {
			if len(label) > 63 {
				return fmt.Errorf("value %q (%s): hostname label exceeds 63 characters", name, value)
			}
		}
	case "url":
		u, err := url.Parse(value)
		if err != nil || u.Scheme == "" || u.Host == "" {
			return fmt.Errorf("value %q (%s): must be a valid URL", name, value)
		}
	case "ip":
		if net.ParseIP(value) == nil {
			return fmt.Errorf("value %q (%s): must be a valid IP address", name, value)
		}
	case "timezone":
		_, err := time.LoadLocation(value)
		if err != nil || strings.EqualFold(value, "local") {
			return fmt.Errorf("value %q (%s): must be a valid IANA timezone (e.g. Europe/Berlin, America/New_York, UTC)", name, value)
		}
	default:
		return fmt.Errorf("value %q: unknown validator %q", name, validator)
	}
	return nil
}

// loadSavedSecrets reads previously persisted secrets from the data directory.
func loadSavedSecrets(dataDir string) map[string]string {
	path := filepath.Join(dataDir, SecretsFileName)
	data, err := os.ReadFile(path) // #nosec G304 -- path is constructed internally
	if err != nil {
		return nil
	}
	var secrets map[string]string
	if err := yaml.Unmarshal(data, &secrets); err != nil {
		slog.Warn("Failed to parse saved secrets", "path", path, "error", err)
		return nil
	}
	return secrets
}

// SaveSecrets writes auto-generated secrets to the data directory so they
// survive remove/deploy cycles when data is kept.
func SaveSecrets(dataDir string, allValues map[string]string, autoGenerated map[string]bool) error {
	if len(autoGenerated) == 0 {
		return nil
	}
	secrets := make(map[string]string, len(autoGenerated))
	for name := range autoGenerated {
		secrets[name] = allValues[name]
	}
	data, err := yaml.Marshal(secrets)
	if err != nil {
		return fmt.Errorf("serializing secrets: %w", err)
	}
	path := filepath.Join(dataDir, SecretsFileName)
	return os.WriteFile(path, data, 0o600) // #nosec G306 -- secrets file, owner-only
}

// SaveSecretsFromState extracts auto-generated secret values from a deployed
// app's state and writes them to the data directory. This provides backwards
// compatibility for deployments created before secret persistence was added.
func SaveSecretsFromState(dataDir string, info *DeployedApp, meta *template.AppMeta) error {
	if meta == nil || info == nil {
		return nil
	}
	autoGenerated := make(map[string]bool)
	for _, v := range meta.Values {
		if v.AutoGen != "" {
			if _, ok := info.Values[v.Name]; ok {
				autoGenerated[v.Name] = true
			}
		}
	}
	return SaveSecrets(dataDir, info.Values, autoGenerated)
}
